#######################################################
#
# DataHandling.py
# Python implementation of the Class DataHandling
# Generated by Enterprise Architect
# Created on:      11-Jun-2019 16:42:03
# Original author: Bethan
#
#######################################################


class DataHandling:
    """This class pre-processes the data requested by the user. It transforms the data
    and keeps a copy of the values and the uncertainties in memory.
    """
    def __examine filenames():
        pass

    def __extract_available_parameters():
        pass

    def extract_filenames():
        pass

    def get_timeseries():
        pass

    def get_timestep():
        pass

    def __read_data():
        pass

    def __transform_data():
        pass