#######################################################
#
# GenerateView.py
# Python implementation of the Class GenerateView
# Generated by Enterprise Architect
# Created on:      11-Jun-2019 16:42:05
# Original author: Bethan
#
#######################################################


class GenerateView:
    """This is the class which pulls together the appropriate dash building blocks in
    order to create the dash view.
    """
    def add_parameter_to_maps():
        pass

    def create_new_view():
        pass

    def __generate_drowpdown():
        pass

    def __generate_maps():
        pass

    def __generate_timeseries():
        pass

    def show_new_timestep():
        pass

    def show_timeseries():
        pass